Add Terraform run trigger to workflows
Included steps to fetch the workspace ID and trigger an HCP Terraform run in both delete-test-snapshots-on-pr-merge and create-prod-snapshot-on-release workflows. Ensures appropriate Terraform actions are executed post PR merge and on release.

diff --git a/.github/workflows/delete-test-snapshots-on-pr-merge.yml b/.github/workflows/delete-test-snapshots-on-pr-merge.yml
--- a/.github/workflows/delete-test-snapshots-on-pr-merge.yml
+++ b/.github/workflows/delete-test-snapshots-on-pr-merge.yml
@@ -12,11 +12,11 @@ jobs:
     defaults:
       run:
         shell: bash
-
     env:
       VULTR_API_URL: https://api.vultr.com/v2/snapshots
       AUTH_HEADER: "Authorization: Bearer ${{ secrets.VULTR_API_KEY }}"
       SNAPSHOT_DESCRIPTION: Discord Bot Server [test-PR#${{ github.event.pull_request.number }}]
+      HCP_TF_API_TOKEN: ${{ secrets.HCP_TF_API_TOKEN }}
 
     steps:
       - name: Fetch snapshots for this PR
@@ -50,3 +50,45 @@ jobs:
             echo "Deleted snapshot: $snapshot_desc ($snapshot_id)"
           done
           echo "Kept the most recent snapshot."
+
+      - name: Get workspace ID by name
+        id: get_workspace_id
+        run: |
+          workspace_id=$(curl -s -X GET \
+            --header "Authorization: Bearer $HCP_TF_API_TOKEN" \
+            --header "Content-Type: application/vnd.api+json" \
+            "https://app.terraform.io/api/v2/organizations/madcow234/workspaces?search%5Bname%5D=discord-bot-server-image-testing" | jq -r '.data[0].id')
+          if [[ -z "$workspace_id" ]]; then
+            echo "Error: Unable to retrieve workspace ID"
+            exit 1
+          else
+            echo "workspace_id=$workspace_id" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Trigger HCP Terraform run
+        run: |
+          curl -X POST \
+            --header "Authorization: Bearer $HCP_TF_API_TOKEN" \
+            --header "Content-Type: application/vnd.api+json" \
+            https://app.terraform.io/api/v2/runs \
+            -d '{
+              "data": {
+                "attributes": {
+                  "is-destroy": true,
+                  "auto-apply": true
+                },
+                "type": "runs",
+                "relationships": {
+                  "workspace": {
+                    "data": {
+                      "type": "workspaces",
+                      "id": "'"${{ steps.get_workspace_id.outputs.workspace_id }}"'"
+                    }
+                  }
+                }
+              }
+            }'
+          if [[ $? -ne 0 ]]; then
+            echo "Error: Unable to trigger workspace run"
+            exit 1
+          fi
